version: "3.8"
services:
  app:
    build:
      context: . # Контекст сборки указывает на корневую директорию
      dockerfile: Dockerfile # Явно указываем имя Dockerfile
    container_name: toncourses_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/app

  db:
    image: postgres:14
    container_name: toncourses_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  ngrok:
    image: ngrok/ngrok:alpine
    container_name: ngrok
    command: http app:8000 # Проксирование на приложение
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
      NGROK_REGION: "eu"
    depends_on:
      - app

volumes:
  db_data: